[package]
name = "entropiter"
description = "A no-dep iterator-compatible frequency and Shannon entropy calculator"
repository = "https://github.com/Herbstein/entropiter"
version = "0.2.1"
edition = "2021"
license = "MIT"

[dependencies]
